#!/usr/bin/env python

from flask import (Flask, request, session, g, redirect, url_for, abort, render_template, flash, Response) # pylint: disable=import-error
app = Flask(__name__)

@app.route('/')
def index():
    user = {'name:' : "Rob'"}
    return render_template('index.html')

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True) #host is required to allow this to be served to an external computer



