#!/usr/bin/env python

import sys
import time
import rospy

from std_msgs.msg import String
from std_msgs.msg import Int32

if __name__=='__main__':
    try:
        #create the ROS node for the application	
        rospy.init_node('bagcutter_command')
        #setup publisher to send bagcutter commands
        pubBagcutter = rospy.Publisher('/bagcutterControl',Int32, queue_size=1)
        time.sleep(.1) 
        pubBagcutter.publish(int(sys.argv[1]))

    except rospy.ROSInterruptException:
        pass
