#!/usr/bin/env python
import rospy
from servosix import ServoSix
from std_msgs.msg import Int32
import time

def callback(data):
    # close sissors to cut and then reopen
    ss.set_servo(1,0)
    ss.set_servo(1,90)

    
def listener():
    rospy.init_node('bagcutterControl', anonymous=True)
    rospy.Subscriber("bagcutterControl", Int32, callback)
    rospy.spin()

if __name__ == '__main__':
    ss= ServoSix()
    listener()