#!/usr/bin/env python

import sys
import rospy # pylint: disable=import-error
from GetJointPose.srv import * # pylint: disable=import-error

def set_joint_pose(clockwise):
  #determine the current joint positions
  rospy.wait_for_service('/robotis/base/get_joint_pose')
  try:
    move_joint = rospy.ServiceProxy('/robotis/base/get_joint_pose', GetJointPose)
    responseJointPose = move_joint()
  except:
    print ("Service call failed")
    exit(-1)
  print (responseJointPose)

if __name__ == "__main__":
  keyboard_input = input ("Press 1 to move Joint 1 clockwise, ! for counter clockwise")
  if keyboard_input == "1":
    set_joint_pose(True)
  elif keyboard_input == "!":
    set_joint_pose(False)
  else:
    pass


